apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ghapp
  template:
    metadata:
      labels:
        app: ghapp
    spec:
      containers:
        - name: ghapp
          image: 837005229064.dkr.ecr.ap-northeast-1.amazonaws.com/ghapp
          ports:
            - containerPort: 3000

