apiVersion: v1
kind: Service
metadata:
  name: ghapp
spec:
  selector:
    app.kubernetes.io/name: ghapp
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  type: LoadBalancer
