apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  
  name: ghapp
  
  annotations:
    
    kubernetes.io/ingress.class: "nginx"
    
    nginx.ingress.kubernetes.io/use-regex: "true"
  
  # nginx.ingress.kubernetes.io/rewrite-target: / 

spec:
  
  rules:

    - http:
        
        paths:

          - path: /(.*)
            
            pathType: Prefix
            
            backend:
              
              service:
                
                name: ghapp
                
                port:
                  
                  number: 80

---

apiVersion: v1

kind: Service

metadata:
  
  name: ghapp
  
  labels:
    
    app: ghapp

spec:
  
  type: ClusterIP
  
  selector:
    
    app: ghapp
  
  ports:

    - port: 80
      
      targetPort: 3001
