name: Deploy to EKS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAWEOW6T24WJRQ3QGT
          aws-secret-access-key: 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
          aws-region: us-east-1
          
      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 421894463161.dkr.ecr.us-east-1.amazonaws.com
          
      - name: Build and tag Docker image
        run: |
          echo 'Creating Image'
          chmod +x ./deployment.sh
          ./deployment.sh
          docker tag ghapp 421894463161.dkr.ecr.us-east-1.amazonaws.com/ghapp
          echo 'Image Created'
 
      - name: Push Docker image to ECR
        run: |
          docker push 421894463161.dkr.ecr.us-east-1.amazonaws.com/ghapp

      - name: Generate kubeconfig
        run: |
          aws eks update-kubeconfig --name ghapp-cluster --kubeconfig kubeconfig
          cat kubeconfig
          kubectl config get-contexts
          kubectl apply -f manifest.yaml
          kubectl apply -f service.yaml
        env:
          KUBECONFIG: kubeconfig

      - name: Deploy to EKS
        run: |
          kubectl config get-contexts
#          kubectl apply -f manifest.yaml
#          kubectl apply -f service.yaml
